Repository FUKUO-KA/soongsil-carries-love, pull requests merged in 2024-12, with the labels that each got.

#24 Feature/#23 home api
  .gitignore
  src/api/endpoints/highschool/highschool-ranking.ts
  src/api/types/response.ts
  src/components/DashBoard/DashBoard.tsx
  src/pages/Home/Home.tsx
  src/types/hightSchool-ranking.type.ts
  src/types/index.ts
  vite.config.ts
Labels: feat

#26 feat: 로그인 회원가입 API 연결
  .gitignore
  package.json
  pnpm-lock.yaml
  src/api/axios.ts
  src/api/endpoints/join.ts
  src/api/endpoints/login.ts
  src/api/endpoints/mail/checkAuthNum.ts
  src/api/endpoints/mail/sendAuthNum.ts
  src/api/types/request.ts
  src/api/types/response.ts
  src/components/CustomTabs/CustomTabs.tsx
  src/components/Panel/LoginPanel/LoginPanel.tsx
  src/components/Panel/RegisterPanel/RegisterPanel.style.ts
  src/components/Panel/RegisterPanel/RegisterPanel.tsx
  src/components/SearchBar/SearchBar.style.ts
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/SearchResult.tsx
  src/components/TextField/TextField.style.ts
  src/components/TextField/TextField.tsx
  src/data/school.json
  src/hooks/useRegisterForm.ts
  src/hooks/useSendEmail.ts
  src/hooks/useVerifyCode.ts
  src/pages/Home/Home.tsx
  src/pages/LoginRegister/LoginRegister.tsx
  src/pages/LoginRegister/RegisterDetail/RegisterDetail.style.ts
  src/pages/LoginRegister/RegisterDetail/RegisterDetail.tsx
  src/pages/LoginRegister/SelectSchool/SelectSchool.tsx
  src/stores/authStore.ts
  src/stores/joinStore.ts
  src/stores/userStore.ts
Labels: feat

#27 feat: 통계화면 관련 API 연결 작업
  pnpm-lock.yaml
  src/api/endpoints/hightschool/gender-ratio.ts
  src/api/endpoints/hightschool/student-count.ts
  src/api/endpoints/hightschool/user-count.ts
  src/api/types/response.ts
  src/components/BarChart/BarChart.tsx
  src/components/FieChart/FieChart.tsx
  src/hooks/useRegisterForm.ts
  src/pages/Home/Home.tsx
Labels: feat

#29 fix: 학번 TextField 유효성 길이 관련 rules 수정
  src/pages/LoginRegister/RegisterDetail/RegisterDetail.tsx
Labels: fix

#38 fix: 자잘한 수정사항들 수정 작업
  index.html
  src/assets/favicon/favicon.svg
  src/components/ChatScreen/ChatComponents/ChatBox/ChatBox.style.ts
  src/components/ChatScreen/Mode/ChatMode/ChatMode.tsx
  src/components/DashBoard/DashBoard.tsx
  src/components/Frame/Frame.style.ts
  src/components/Panel/LoginPanel/LoginPanel.tsx
  src/components/Panel/RegisterPanel/RegisterPanel.tsx
  src/components/TextField/TextField.tsx
  src/pages/Home/Home.tsx
  src/pages/LoginRegister/RegisterDetail/RegisterDetail.tsx
Labels: fix

#40 feat: 로그인/비로그인 별 홈 화면 설정
  index.html
  src/App.tsx
  src/components/Modal/Modal.style.ts
  src/components/Modal/Modal.tsx
  src/components/Panel/LoginPanel/LoginPanel.tsx
  src/components/Profile/Profile.style.ts
  src/components/Profile/Profile.tsx
  src/pages/Home/Home.tsx
  src/types/homeSection.type.ts
Labels: feat, fix
